/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.controladorDAO.CursoAcademicoDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.CursoAcademico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author sergio
 */
public class frmMain extends javax.swing.JFrame {

    public static int idCursoAcademico=0; 
    private JLabel statusLabel;
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        JPanel status = new JPanel();
        statusLabel = new JLabel("");
        status.add( statusLabel );
        this.getContentPane().add(status, BorderLayout.SOUTH);
        
        generaMenuCursosAcademicos();
        //System.out.println("Generado menu");
    }

    
    public void generaMenuCursosAcademicos(){
        
        /*JRadioButtonMenuItem jrb23=new JRadioButtonMenuItem("2022-2023", true);
        JRadioButtonMenuItem jrb22=new JRadioButtonMenuItem("2021-2022", false);
        JRadioButtonMenuItem jrb21=new JRadioButtonMenuItem("2020-2021", false);
        
        ButtonGroup bgrCursosAcademicos=new ButtonGroup();
        
        jmnCursoAcademico.add(jrb23);
        bgrCursosAcademicos.add(jrb23);
        jmnCursoAcademico.add(jrb22);
        bgrCursosAcademicos.add(jrb22);
        jmnCursoAcademico.add(jrb21);
        bgrCursosAcademicos.add(jrb21);
        */
                
        ButtonGroup bgrCursosAcademicos=new ButtonGroup();
        JRadioButtonMenuItem jrbCursoAcademico;
        
        CursoAcademicoDaoImp cursoaca=CursoAcademicoDaoImp.getInstance();
        
        try{
            List<CursoAcademico> lst=cursoaca.getAll();
            
                for( CursoAcademico curso :lst){
                    jrbCursoAcademico=new JRadioButtonMenuItem(""+curso.getDescripcion(), true);                    
                    jrbCursoAcademico.setName(""+curso.getId());
                    if (idCursoAcademico==0){
                        idCursoAcademico=curso.getId();
                        statusLabel.setText(""+curso.getDescripcion());
                    }
                    bgrCursosAcademicos.add(jrbCursoAcademico);
                    jmnCursoAcademico.add(jrbCursoAcademico); 
                    
                    jrbCursoAcademico.addItemListener(new ItemListener(){
                        
                        public void itemStateChanged(ItemEvent e){
                            
                            JRadioButtonMenuItem jrbSelected=(JRadioButtonMenuItem)e.getItem();
                            idCursoAcademico=Integer.parseInt(jrbSelected.getName());
                            System.out.println(""+idCursoAcademico);
                            statusLabel.setText(jrbSelected.getText());
                            
                        }
                        
                    });
                    
                    
                }
        }catch(Exception e){
            System.out.println("Error..."+e.getMessage());
        }
    
    }

    private boolean existeFormulario(Object object){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            System.out.println(""+frmcargados[i].getClass());
            if (frmcargados[i].getClass()==object.getClass()){
                return true;
            }
            
        }
        return false;
    }
    
    
    private boolean existeFormularioV2(String nombreclase){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            
            if (frmcargados[i].getClass().equals(nombreclase)){
                return true;
            }
            
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnldEscritorio = new javax.swing.JDesktopPane();
        btnIniciar = new javax.swing.JButton();
        btnCursoAcademico = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jmnCursoAcademico = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        optmAcerca = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnCursoAcademico.setText("Curso Academico");
        btnCursoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoAcademicoActionPerformed(evt);
            }
        });

        pnldEscritorio.setLayer(btnIniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnldEscritorio.setLayer(btnCursoAcademico, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnldEscritorioLayout = new javax.swing.GroupLayout(pnldEscritorio);
        pnldEscritorio.setLayout(pnldEscritorioLayout);
        pnldEscritorioLayout.setHorizontalGroup(
            pnldEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnCursoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnldEscritorioLayout.setVerticalGroup(
            pnldEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldEscritorioLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(pnldEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCursoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(pnldEscritorio, java.awt.BorderLayout.CENTER);

        jmnCursoAcademico.setText("Año Academico");
        menuBar.add(jmnCursoAcademico);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        optmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAcerca.setMnemonic('a');
        optmAcerca.setText("Acerca de");
        optmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(optmAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAcercaActionPerformed
        // TODO add your handling code here:
      frmAcercaDeDialogo frmacerca=new frmAcercaDeDialogo(this, rootPaneCheckingEnabled);
      frmacerca.setVisible(true);
        
    }//GEN-LAST:event_optmAcercaActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        frmCurso w_curso = new frmCurso();        w_curso.setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCursoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoAcademicoActionPerformed
        // TODO add your handling code here:
        frmCursoAcademico w_CursoAcademico = new frmCursoAcademico();
        w_CursoAcademico.setVisible(true);
    }//GEN-LAST:event_btnCursoAcademicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursoAcademico;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmnCursoAcademico;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem optmAcerca;
    private javax.swing.JDesktopPane pnldEscritorio;
    // End of variables declaration//GEN-END:variables

}
